-- TODOS OS TIPOS DE PGAMANETO
SELECT ID_TIPO_PAGAMENTO,
       NO_TIPO_PAGAMENTO
FROM TIPO_PAGAMENTO;

-- TODOS OS QUARTOS
SELECT T1.ID_QUARTO,
       T1.NU_QUARTO,
       T2.ID_TIPO_QUARTO,
       T2.NO_TIPO_QUARTO
FROM QUARTO T1
LEFT JOIN TIPO_QUARTO T2;