CREATE VIEW IF NOT EXISTS VW_QUARTO_DISPONIVEL AS
SELECT	NU_QUARTO,
		IN_DISPONIVEL,
		NO_TIPO_QUARTO,
		VL_DIARIA
FROM QUARTO
LEFT JOIN TIPO_QUARTO ON QUARTO.ID_TIPO_QUARTO = TIPO_QUARTO.ID_TIPO_QUARTO
WHERE QUARTO.IN_DISPONIVEL = 1;

CREATE VIEW IF NOT EXISTS VW_QUARTO_INDISPONIVEL AS
SELECT	NU_QUARTO,
		IN_DISPONIVEL,
		NO_TIPO_QUARTO,
		VL_DIARIA
FROM QUARTO
LEFT JOIN TIPO_QUARTO ON QUARTO.ID_TIPO_QUARTO = TIPO_QUARTO.ID_TIPO_QUARTO
WHERE QUARTO.IN_DISPONIVEL = 0;
