-- QUARTO E SEU TIPO
CREATE VIEW IF NOT EXISTS VW_QUARTO_TIPO_QUARTO AS
SELECT  T1.ID_QUARTO,
		T1.NU_QUARTO,
		T1.ID_TIPO_QUARTO ID_TIPO_QUARTO,
        T2.NO_TIPO_QUARTO,
        T2.VL_DIARIA
FROM QUARTO T1
LEFT JOIN TIPO_QUARTO T2 ON T1.ID_TIPO_QUARTO = T2.ID_TIPO_QUARTO;

-- QUARTO INDISPONIVEL E SEU TIPO
CREATE VIEW IF NOT EXISTS VW_QUARTO_INDISPONIVEL AS
SELECT 	T2.*,
		T3.NO_TIPO_QUARTO,
		T3.VL_DIARIA
FROM HOSPEDAGEM T1
LEFT JOIN QUARTO T2 ON T1.ID_QUARTO = T2.ID_QUARTO
LEFT JOIN TIPO_QUARTO T3 ON T2.ID_TIPO_QUARTO = T3.ID_TIPO_QUARTO
WHERE T1.IN_ATIVO = 1;

-- QUARTO DISPONIVEL E SEU TIPO
CREATE VIEW IF NOT EXISTS VW_QUARTO_DISPONIVEL AS
SELECT 	T1.*,
		T3.NO_TIPO_QUARTO,
		T3.VL_DIARIA
FROM QUARTO T1
LEFT JOIN VW_QUARTO_INDISPONIVEL T2 ON T1.ID_QUARTO = T2.ID_QUARTO
LEFT JOIN TIPO_QUARTO T3 ON T1.ID_TIPO_QUARTO = T3.ID_TIPO_QUARTO
WHERE T2.ID_QUARTO IS NULL;

-- FUNCIONARIO E SEU ENDERECO
CREATE VIEW IF NOT EXISTS VW_FUNCIONARIO_ENDERECO AS
SELECT 	T1.ID_FUNCIONARIO,
		T1.NU_CPF,
		T1.NO_FUNCIONARIO,
		T1.NU_TELEFONE,
		T1.NO_EMAIL,
		T1.ID_ENDERECO,
		T2.NU_CEP,
		T2.NO_ENDERECO,
		T2.NO_COMPLEMENTO,
		T2.NU_NUMERO
FROM FUNCIONARIO T1
LEFT JOIN ENDERECO T2 ON T1.ID_ENDERECO = T2.ID_ENDERECO;

-- HOSPEDE E SEU ENDERECO
CREATE VIEW IF NOT EXISTS VW_HOSPEDE_ENDERECO AS
SELECT 	T1.ID_HOSPEDE,
		T1.NU_CPF,
		T1.NO_HOSPEDE,
		T1.NU_TELEFONE,
		T1.NO_EMAIL,
		T1.ID_ENDERECO,
		T2.NU_CEP,
		T2.NO_ENDERECO,
		T2.NO_COMPLEMENTO,
		T2.NU_NUMERO
FROM HOSPEDE T1
LEFT JOIN ENDERECO T2 ON T1.ID_ENDERECO = T2.ID_ENDERECO;

-- HOSPEDAGEM COMPLETA
CREATE VIEW IF NOT EXISTS VW_HOSPEDAGEM_COMPLETA AS
SELECT 	T2.ID_FUNCIONARIO,
		T2.NU_CPF NU_CPF_FUNCIONARIO,
		T2.NO_FUNCIONARIO,
		T3.ID_QUARTO,
		T3.NU_QUARTO,
		T4.ID_TIPO_PAGAMENTO,
		T4.NO_TIPO_PAGAMENTO,
		
		T1.ID_HOSPEDE_TITULAR,
		T5.NU_CPF NU_CPF_TITLAR,
		T5.NO_HOSPEDE NO_HOSPEDE_TITULAR,
		
		T1.ID_HOSPEDE_ACOMPANHANTE_1,
		T6.NU_CPF NU_CPF_ACOMPANHANTE_1,
		T6.NO_HOSPEDE NO_HOSPEDE_ACOMPANHANTE_1,
		
		T1.ID_HOSPEDE_ACOMPANHANTE_2,
		T7.NU_CPF NU_CPF_ACOMPANHANTE_2,
		T7.NO_HOSPEDE NO_HOSPEDE_ACOMPANHANTE_2,
		
		T1.ID_HOSPEDE_ACOMPANHANTE_3,
		T8.NU_CPF NU_CPF_ACOMPANHANTE_3,
		T8.NO_HOSPEDE NO_HOSPEDE_ACOMPANHANTE_3,
		
		T1.IN_ATIVO,
		T1.DT_ENTRADA,
		T1.NU_NOITE,
		T1.VL_HOSPEDAGEM
FROM HOSPEDAGEM T1
LEFT JOIN FUNCIONARIO T2 ON T1.ID_FUNCIONARIO = T2.ID_FUNCIONARIO
LEFT JOIN QUARTO T3 ON T1.ID_QUARTO = T3.ID_QUARTO
LEFT JOIN TIPO_PAGAMENTO T4 ON T1.ID_TIPO_PAGAMENTO = T4.ID_TIPO_PAGAMENTO
LEFT JOIN HOSPEDE T5 ON T1.ID_HOSPEDE_TITULAR = T5.ID_HOSPEDE
LEFT JOIN HOSPEDE T6 ON T1.ID_HOSPEDE_ACOMPANHANTE_1 = T6.ID_HOSPEDE
LEFT JOIN HOSPEDE T7 ON T1.ID_HOSPEDE_ACOMPANHANTE_2 = T7.ID_HOSPEDE
LEFT JOIN HOSPEDE T8 ON T1.ID_HOSPEDE_ACOMPANHANTE_3 = T8.ID_HOSPEDE;