CREATE UNIQUE INDEX IF NOT EXISTS "IX_FUNCIONARIO_CPF" ON "FUNCIONARIO" (
	"NU_CPF"
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_HOSPEDE_CPF" ON "HOSPEDE" (
	"NU_CPF"
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_QUARTO_NUMERO" ON "QUARTO" (
	"NU_QUARTO"
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_NOME_TIPO_PAGAMENTO" ON "TIPO_PAGAMENTO" (
	"NO_TIPO_PAGAMENTO"
);