CREATE UNIQUE INDEX IF NOT EXISTS "IX_FUNCIONARIO_CPF" ON "FUNCIONARIO" (
	"NU_CPF"
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_HOSPEDE_CPF" ON "HOSPEDE" (
	"NU_CPF"
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_QUARTO_NUMERO" ON "QUARTO" (
	"NU_QUARTO"
);