-- ENDERECO
CREATE TRIGGER IF NOT EXISTS TR_ENDERECO_BEFORE_INSERT_VALIDA_DADOS
   BEFORE INSERT ON "ENDERECO"
BEGIN
    SELECT
        CASE
            WHEN NEW.NU_CEP NOT LIKE "________" THEN
                RAISE (ABORT, "NUMERO DE CEP INVALIDO")
        END;
END;

CREATE TRIGGER IF NOT EXISTS TR_ENDERECO_BEFORE_UPDATE_VALIDA_DADOS
   BEFORE UPDATE ON "ENDERECO"
BEGIN
    SELECT
        CASE
            WHEN NEW.NU_CEP NOT LIKE "________" THEN
                RAISE (ABORT, "NUMERO DE CEP INVALIDO")
        END;
END;

-- FUNCIONARIO
CREATE TRIGGER IF NOT EXISTS TR_FUNCIONARIO_BEFORE_INSERT_VALIDA_DADOS
   BEFORE INSERT ON "FUNCIONARIO"
BEGIN
    SELECT
        CASE
            WHEN NEW.NU_CPF NOT LIKE "___________" THEN
                RAISE (ABORT, "NUMERO DE CPF INVALIDO")
            WHEN NEW.NU_TELEFONE NOT LIKE "___________" THEN
                RAISE (ABORT, "NUMERO DE TELEFONE INVALIDO")
            WHEN NEW.NO_EMAIL NOT LIKE '%_@__%.__%' THEN
                RAISE (ABORT,'EMAIL INVALIDO')
        END;
END;

CREATE TRIGGER IF NOT EXISTS TR_FUNCIONARIO_BEFORE_UPDATE_VALIDA_DADOS
   BEFORE UPDATE ON "FUNCIONARIO"
BEGIN
    SELECT
        CASE
            WHEN NEW.NU_CPF NOT LIKE "___________" THEN
                RAISE (ABORT, "NUMERO DE CPF INVALIDO")
            WHEN NEW.NU_TELEFONE NOT LIKE "___________" THEN
                RAISE (ABORT, "NUMERO DE TELEFONE INVALIDO")
            WHEN NEW.NO_EMAIL NOT LIKE '%_@__%.__%' THEN
                RAISE (ABORT,'EMAIL INVALIDO')
        END;
END;

-- HOSPEDE
CREATE TRIGGER IF NOT EXISTS TR_HOSPEDE_BEFORE_INSERT_VALIDA_DADOS
   BEFORE INSERT ON "HOSPEDE"
BEGIN
    SELECT
        CASE
            WHEN NEW.NU_CPF NOT LIKE "___________" THEN
                RAISE (ABORT, "NUMERO DE CPF INVALIDO")
            WHEN NEW.NU_TELEFONE NOT LIKE "___________" THEN
                RAISE (ABORT, "NUMERO DE TELEFONE INVALIDO")
            WHEN NEW.NO_EMAIL NOT LIKE '%_@__%.__%' THEN
                RAISE (ABORT,'EMAIL INVALIDO')
        END;
END;

CREATE TRIGGER IF NOT EXISTS TR_HOSPEDE_BEFORE_UPDATE_VALIDA_DADOS
   BEFORE UPDATE ON "HOSPEDE"
BEGIN
    SELECT
        CASE
            WHEN NEW.NU_CPF NOT LIKE "___________" THEN
                RAISE (ABORT, "NUMERO DE CPF INVALIDO")
            WHEN NEW.NU_TELEFONE NOT LIKE "___________" THEN
                RAISE (ABORT, "NUMERO DE TELEFONE INVALIDO")
            WHEN NEW.NO_EMAIL NOT LIKE '%_@__%.__%' THEN
                RAISE (ABORT,'EMAIL INVALIDO')
        END;
END;

-- HOSPEDAGEM
CREATE TRIGGER TR_HOSPEDAGEM_AFTER_INSERT_PREENCHE_VALOR
   AFTER INSERT ON "HOSPEDAGEM"
BEGIN
    SELECT
        CASE
            WHEN QUARTO.IN_DISPONIVEL = 0 THEN
                RAISE (ABORT, "QUARTO NAO ESTA DISPONIVEL")
            WHEN NEW.DT_ENTRADA NOT LIKE "__/__/____" THEN
                RAISE (ABORT, "DATA DE ENTRADA INVALIDA")
		END
    FROM QUARTO
    WHERE QUARTO.ID_QUARTO = NEW.ID_QUARTO;

    UPDATE "HOSPEDAGEM"
    SET "VL_HOSPEDAGEM" = (
        SELECT SUM(NEW.NU_NOITE * T2.VL_DIARIA)
        FROM QUARTO T1
        LEFT JOIN TIPO_QUARTO T2 ON T1.ID_TIPO_QUARTO = T2.ID_TIPO_QUARTO
        WHERE T1.ID_QUARTO = NEW.ID_QUARTO
    ) WHERE ID_HOSPEDAGEM = NEW.ID_HOSPEDAGEM;

    UPDATE "QUARTO"
    SET "IN_DISPONIVEL" = 0
    WHERE ID_QUARTO = NEW.ID_QUARTO;
END;