-- DELETA TIPO_PAGAMENTO
DELETE FROM "TIPO_PAGAMENTO"
WHERE "ID_TIPO_PAGAMENTO" = <ID_TIPO_PAGAMENTO>;

-- DELETA TIPO_QUARTO
DELETE FROM "TIPO_QUARTO"
WHERE "ID_TIPO_QUARTO" = <ID_TIPO_QUARTO>;

-- DELETA QUARTO
DELETE FROM "QUARTO"
WHERE "NU_QUARTO" = <NU_QUARTO>;