-- ALTERAR VALOR DA DIÁRIA
UPDATE "TIPO_PAGAMENTO"
SET "VL_DIARIA" = <NOVO_VALOR_DIAROA>
WHERE "ID_TIPO_PAGAMENTO" = <ID_TIPO_PAGAMENTO>

-- ALTERAR DADOS DO FUNCIONÁRIO
UPDATE "FUNCIONARIO"
SET "NO_EMAIL" = <NOVO_EMAIL>,
    "NU_TELEFONE" = <NOVO_TELEFONE>
WHERE "ID_FUNCIONARIO" = <ID_FUNCIONARIO>

UPDATE "ENDERECO"
SET "NO_CEP" = <NOVO_CEP>,
    "NO_ENDERECO" = <NOVO_ENDERECO>,
    "NO_COMPLEMENTE" = <NOVO_COMPLEMENTO>,
    "NU_NUMERO" = <NOVO_NUMERO>
WHERE "ID_ENDERECO" = <ID_ENDERECO>

-- ALTERAR DADOS DO HOSPEDE
UPDATE "HOSPEDE"
SET "NO_EMAIL" = <NOVO_EMAIL>,
    "NU_TELEFONE" = <NOVO_TELEFONE>
WHERE "ID_HOSPEDE" = <ID_HOSPEDE>

UPDATE "ENDERECO"
SET "NO_CEP" = <NOVO_CEP>,
    "NO_ENDERECO" = <NOVO_ENDERECO>,
    "NO_COMPLEMENTE" = <NOVO_COMPLEMENTO>,
    "NU_NUMERO" = <NOVO_NUMERO>
WHERE "ID_ENDERECO" = <ID_ENDERECO>