-- TIPO_QUARTO
INSERT INTO TIPO_QUARTO VALUES (NULL, '1 CAMA DE SOLTEIRO', 80);
INSERT INTO TIPO_QUARTO VALUES (NULL, '2 CAMA DE SOLTEIRO', 160);
INSERT INTO TIPO_QUARTO VALUES (NULL, '1 CAMA DE CASAL', 150);
INSERT INTO TIPO_QUARTO VALUES (NULL, '2 CAMA DE CASAL', 300);
INSERT INTO TIPO_QUARTO VALUES (NULL, '1 CAMA DE CASAL + 1 CAMA DE SOLTEIRO', 230);
INSERT INTO TIPO_QUARTO VALUES (NULL, '1 CAMA DE CASAL + 2 CAMA DE SOLTEIRO', 310);
COMMIT;

-- TIPO_PAGAMENTO
INSERT INTO TIPO_PAGAMENTO VALUES (NULL, 'DINHEIRO');
INSERT INTO TIPO_PAGAMENTO VALUES (NULL, 'CARTAO DE DEBITO');
INSERT INTO TIPO_PAGAMENTO VALUES (NULL, 'CARTAO DE CREDITO');
INSERT INTO TIPO_PAGAMENTO VALUES (NULL, 'BITCOIN');
COMMIT;

-- QUARTO
INSERT INTO QUARTO VALUES (NULL, 100, 1, 1);
INSERT INTO QUARTO VALUES (NULL, 200, 1, 1);
INSERT INTO QUARTO VALUES (NULL, 110, 1, 2);
INSERT INTO QUARTO VALUES (NULL, 210, 1, 2);
INSERT INTO QUARTO VALUES (NULL, 120, 1, 3);
INSERT INTO QUARTO VALUES (NULL, 220, 1, 3);
INSERT INTO QUARTO VALUES (NULL, 130, 1, 4);
INSERT INTO QUARTO VALUES (NULL, 230, 1, 4);
INSERT INTO QUARTO VALUES (NULL, 140, 1, 5);
INSERT INTO QUARTO VALUES (NULL, 240, 1, 5);
INSERT INTO QUARTO VALUES (NULL, 150, 1, 6);
INSERT INTO QUARTO VALUES (NULL, 250, 1, 6);
COMMIT;
