-- FUNCIONÁRIOS
INSERT INTO "ENDERECO" ("NU_CEP", "NO_ENDERECO", "NO_COMPLEMENTO", "NU_NUMERO")
VALUES ("70705000", "SETOR HOTELEIRO NORTE, QUADRA 05 BLOCO A", "APARTAMENTO", 100);
INSERT INTO "FUNCIONARIO" ("NU_CPF", "NO_FUNCIONARIO", "NU_TELEFONE", "NO_EMAIL", "ID_ENDERECO")
VALUES ("99860033005", "JOSÉ FELIPE DA SILVA", 61986482439, "JOSE@GMAIL.COM", 1);

INSERT INTO "ENDERECO" ("NU_CEP", "NO_ENDERECO", "NO_COMPLEMENTO", "NU_NUMERO")
VALUES ("70705000", "SETOR HOTELEIRO NORTE, QUADRA 05 BLOCO B", "APARTAMENTO", 200);
INSERT INTO "FUNCIONARIO" ("NU_CPF", "NO_FUNCIONARIO", "NU_TELEFONE", "NO_EMAIL", "ID_ENDERECO")
VALUES ("97101759027", "MARIA CLARA OLIVEIRA", 61986435985, "MARIA@GMAIL.COM", 2);

INSERT INTO "ENDERECO" ("NU_CEP", "NO_ENDERECO", "NO_COMPLEMENTO", "NU_NUMERO")
VALUES ("70705000", "SETOR HOTELEIRO NORTE, QUADRA 05 BLOCO C", "APARTAMENTO", 300);
INSERT INTO "FUNCIONARIO" ("NU_CPF", "NO_FUNCIONARIO", "NU_TELEFONE", "NO_EMAIL", "ID_ENDERECO")
VALUES ("04817019375", "MÁCIO DE OLÁVIO", 61999865357, "MACIO@GMAIL.COM", 3);

INSERT INTO "ENDERECO" ("NU_CEP", "NO_ENDERECO", "NO_COMPLEMENTO", "NU_NUMERO")
VALUES ("70705000", "SETOR HOTELEIRO NORTE, QUADRA 05 BLOCO D", "APARTAMENTO", 400);
INSERT INTO "FUNCIONARIO" ("NU_CPF", "NO_FUNCIONARIO", "NU_TELEFONE", "NO_EMAIL", "ID_ENDERECO")
VALUES ("81058265830", "MARCO JOSÉ PEREIRA", 61987643581, "MARCO@GMAIL.COM", 4);

INSERT INTO "ENDERECO" ("NU_CEP", "NO_ENDERECO", "NO_COMPLEMENTO", "NU_NUMERO")
VALUES ("70705000", "SETOR HOTELEIRO NORTE, QUADRA 05 BLOCO E", "APARTAMENTO", 500);
INSERT INTO "FUNCIONARIO" ("NU_CPF", "NO_FUNCIONARIO", "NU_TELEFONE", "NO_EMAIL", "ID_ENDERECO")
VALUES ("10386730129", "CARLA DE HOLANDA", 61986456439, "CARLA@GMAIL.COM", 5);

-- HÓSPEDES
INSERT INTO "ENDERECO" ("NU_CEP", "NO_ENDERECO", "NO_COMPLEMENTO", "NU_NUMERO")
VALUES ("72851370", "RUA 14 PARQUE NOVA IGUAÇU LUZIÂNIA", "CASA", 10);
INSERT INTO "HOSPEDE" ("NU_CPF", "NO_HOSPEDE", "NU_TELEFONE", "NO_EMAIL", "ID_ENDERECO")
VALUES ("99860033005", "LEILA SOARES", 61986482439, "LEILA@GMAIL.COM", 6);

INSERT INTO "ENDERECO" ("NU_CEP", "NO_ENDERECO", "NO_COMPLEMENTO", "NU_NUMERO")
VALUES ("72851370", "RUA 14 PARQUE NOVA IGUAÇU LUZIÂNIA", "CASA", 12);
INSERT INTO "HOSPEDE" ("NU_CPF", "NO_HOSPEDE", "NU_TELEFONE", "NO_EMAIL", "ID_ENDERECO")
VALUES ("97101759027", "RITA DE CÁSSIA", 61986435985, "RITA@GMAIL.COM", 7);

INSERT INTO "ENDERECO" ("NU_CEP", "NO_ENDERECO", "NO_COMPLEMENTO", "NU_NUMERO")
VALUES ("72851370", "RUA 14 PARQUE NOVA IGUAÇU LUZIÂNIA", "CASA", 14);
INSERT INTO "HOSPEDE" ("NU_CPF", "NO_HOSPEDE", "NU_TELEFONE", "NO_EMAIL", "ID_ENDERECO")
VALUES ("04817019375", "FABIANE OLIVEIRA", 61999865357, "FABIANE@GMAIL.COM", 8);

INSERT INTO "ENDERECO" ("NU_CEP", "NO_ENDERECO", "NO_COMPLEMENTO", "NU_NUMERO")
VALUES ("72851370", "RUA 14 PARQUE NOVA IGUAÇU LUZIÂNIA", "CASA", 16);
INSERT INTO "HOSPEDE" ("NU_CPF", "NO_HOSPEDE", "NU_TELEFONE", "NO_EMAIL", "ID_ENDERECO")
VALUES ("81058265830", "FABINO CARLOS", 61987643581, "FABINO@GMAIL.COM", 9);

INSERT INTO "ENDERECO" ("NU_CEP", "NO_ENDERECO", "NO_COMPLEMENTO", "NU_NUMERO")
VALUES ("72851370", "RUA 14 PARQUE NOVA IGUAÇU LUZIÂNIA", "CASA", 18);
INSERT INTO "HOSPEDE" ("NU_CPF", "NO_HOSPEDE", "NU_TELEFONE", "NO_EMAIL", "ID_ENDERECO")
VALUES ("10386730129", "VITOR NUNES", 61986456439, "VITOR@GMAIL.COM", 10);

-- TIPO DE QUARTO
INSERT INTO "TIPO_QUARTO" ("NO_TIPO_QUARTO", "VL_DIARIA")
VALUES ("1 CAMA DE SOLTEIRO", 50.0);

INSERT INTO "TIPO_QUARTO" ("NO_TIPO_QUARTO", "VL_DIARIA")
VALUES ("2 CAMAS DE SOLTEIRO", 100.0);

INSERT INTO "TIPO_QUARTO" ("NO_TIPO_QUARTO", "VL_DIARIA")
VALUES ("3 CAMAS DE SOLTEIRO", 150.0);

INSERT INTO "TIPO_QUARTO" ("NO_TIPO_QUARTO", "VL_DIARIA")
VALUES ("4 CAMAS DE SOLTEIRO", 200.0);

INSERT INTO "TIPO_QUARTO" ("NO_TIPO_QUARTO", "VL_DIARIA")
VALUES ("1 CAMA DE CASAL", 120.0);

INSERT INTO "TIPO_QUARTO" ("NO_TIPO_QUARTO", "VL_DIARIA")
VALUES ("1 CAMA DE CASAL E 1 DE SOLTEIRO", 170.0);

INSERT INTO "TIPO_QUARTO" ("NO_TIPO_QUARTO", "VL_DIARIA")
VALUES ("1 CAMA DE CASAL E 2 DE SOLTEIRO", 220.0);

INSERT INTO "TIPO_QUARTO" ("NO_TIPO_QUARTO", "VL_DIARIA")
VALUES ("2 CAMAS DE CASAL", 240.0);

-- QUARTO
INSERT INTO "QUARTO" ("NU_QUARTO", "ID_TIPO_QUARTO")
VALUES (100, 1);

INSERT INTO "QUARTO" ("NU_QUARTO", "ID_TIPO_QUARTO")
VALUES (200, 2);

INSERT INTO "QUARTO" ("NU_QUARTO", "ID_TIPO_QUARTO")
VALUES (110, 3);

INSERT INTO "QUARTO" ("NU_QUARTO", "ID_TIPO_QUARTO")
VALUES (210, 4);

INSERT INTO "QUARTO" ("NU_QUARTO", "ID_TIPO_QUARTO")
VALUES (120, 5);

INSERT INTO "QUARTO" ("NU_QUARTO", "ID_TIPO_QUARTO")
VALUES (220, 6);

INSERT INTO "QUARTO" ("NU_QUARTO", "ID_TIPO_QUARTO")
VALUES (130, 7);

INSERT INTO "QUARTO" ("NU_QUARTO", "ID_TIPO_QUARTO")
VALUES (230, 8);

-- TIPO PAGAMANETO
INSERT INTO "TIPO_PAGAMENTO" ("NO_TIPO_PAGAMENTO")
VALUES ("DINHEIRO");

INSERT INTO "TIPO_PAGAMENTO" ("NO_TIPO_PAGAMENTO")
VALUES ("CARTÃO DE DÉBITO");

INSERT INTO "TIPO_PAGAMENTO" ("NO_TIPO_PAGAMENTO")
VALUES ("CARTÃO DE CRÉDITO");

INSERT INTO "TIPO_PAGAMENTO" ("NO_TIPO_PAGAMENTO")
VALUES ("TELESENA");

INSERT INTO "TIPO_PAGAMENTO" ("NO_TIPO_PAGAMENTO")
VALUES ("BITCOING");